version: '3'

services:
  code_api:
    container_name: code_api
    # container_name: flask_app
    restart: always
    build: ../code_api
    # build: ./flask_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ../nginx
    # build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - code_api