version: '3'

services:
  code_walk:
    container_name: code_walk
    restart: always
    build: ../code_walk
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    # networks:
      # backend:
  nginx_conf:
    container_name: ng
    restart: always
    build: ../nginx_conf
    ports:
      - "80:80"
    depends_on:
      - code_walk
    # networks:
      # backend:
# networks:
  # backend: